### ISSUE TITLE
Home Assistant settings keep being forgotten

### ISSUE THREAD

**Issue by stevelord** [MycroftAI/skill-homeassistant#9] opened 2019-05-08 09:16 UTC
Mycroft is up and running, but Mycroft won't remember settings.

To recreate:

1. Install the Home Assistant plugin from the marketplace
2. Enter a server, token and port, uncheck verify.
3. Hit save.
4. Say, "Hey mycroft, turn on bedroom light"
5. Start crying when mycroft tells you to configure the home assistant settings.

I've tried removing and re-adding the plugin, manually writing into settings.json, nothing works.

Any idea what's happening, or how I can figure out what's happening?

**Comment by merps** [comment] 2019-05-09 05:06
@stevelord - curious, have you got multiple mycroft's configured with this skill?

**Comment by stevelord** [comment] 2019-05-09 09:26
Just the one. It's a fresh build using the 2018-09-02 image. Home assistant is on the same network but doesn't use SSL.

**Comment by renekliment** [comment] 2019-05-11 11:08
I'm having the same issue here.

**Comment by renekliment** [comment] 2019-05-12 13:21
I think this is an issue with `home.mycroft.ai` exclusively. It gives me `503`s when trying to save settings.

**Comment by renekliment** [comment] 2019-05-12 13:32
Sorry for the spam, but I've tried in an anonymous window and that seems to work!

**Comment by merps** [comment] 2019-05-16 12:38
cheers @stevelord - `503` - where are you seeing that @renekliment ?

**Comment by JonathanBlasingame** [comment] 2019-05-17 21:31
Has the issue been resolved yet?

**Comment by peterdolenc** [comment] 2019-05-21 09:10
I don't think it has been fixed. Here's what's worked for me (workaround):
- put in your data and check to use SSL and to validate it (all 3 checkboxes checked)
- save -> this will work
- reload page
- uncheck SSL checkboxes 
- save (the rest will  stick now)

EDIT: or not... it somehow worked for a brief period :/

**Comment by Fmstrat** [comment] 2020-08-01 20:11
I'm having the same issue, as well. Has anyone solved this one?

**Comment by krisgesling** [comment] 2020-08-03 00:07
One issue is that if `settingsmeta.json` is modified then the backend treats it as a new settings block and doesn't currently have a mechanism to copy data across from previous settings. This is something we've got on the backlog to look at but have other priorities at the moment. 

Is there a chance that this was the cause, or is it dropping the settings when this file hasn't been updated?

**Comment by stratus-ss** [comment] 2021-11-16 15:16
I am closing this issue as it is over a year old. If users are still experiencing problems feel free to reopen this

**Closed as completed by stratus-ss** 2021-11-16 15:16 UTC
